# Generated by Django 4.2.5 on 2023-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='team',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
