# Generated by Django 4.2.5 on 2023-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_nbaplayer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='assists_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='points_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='rebounds_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
