# Generated by Django 4.2.6 on 2023-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateTimeField()),
                ('gametime', models.TimeField()),
                ('hometeam', models.CharField(default='Default Home Team', max_length=255)),
                ('awayteam', models.CharField(default='Default Away Team', max_length=255)),
                ('hometeam_logo', models.URLField(default='https://example.com/default-home-logo.png')),
                ('awayteam_logo', models.URLField(default='https://example.com/default-away-logo.png')),
            ],
        ),
        migrations.CreateModel(
            name='NBAPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.CharField(default='Unknown', max_length=50)),
                ('PPG', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('APG', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('RPG', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('SPG', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('BPG', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('FG_PCT', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('FG3_PCT', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('FT_PCT', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('MIN', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('TOV', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
