# Generated by Django 4.2.6 on 2023-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='awayteamscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='hometeamscore',
            field=models.IntegerField(default=0),
        ),
    ]
