# Generated by Django 4.2.6 on 2024-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_fixture_awayteamscore_fixture_hometeamscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('logo', models.URLField()),
                ('all_star', models.BooleanField(default=False)),
                ('nba_franchise', models.BooleanField(default=True)),
                ('conference', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
