# Generated by Django 4.2.6 on 2024-01-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(default='', max_length=50),
        ),
    ]
