# Generated by Django 4.2.6 on 2024-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_team_conference_alter_team_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
