# Generated by Django 4.2.6 on 2024-03-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_profile_bio_profile_favorite_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.team'),
        ),
    ]
