# Generated by Django 4.2.6 on 2024-03-18 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_fantasyteam_profile_fantasy_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='players',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player10_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player3_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player4_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player5_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player6_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player7_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player8_fantasy_team', to='mysite.nbaplayer'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='player9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player9_fantasy_team', to='mysite.nbaplayer'),
        ),
    ]
