# Generated by Django 4.2.6 on 2024-03-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_remove_fantasyteam_players_fantasyteam_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fantasy_team',
        ),
    ]
