# Generated by Django 4.2.6 on 2024-03-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_profile_fantasy_team'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fantasyteam',
            constraint=models.UniqueConstraint(fields=('player1', 'player2', 'player3', 'player4', 'player5', 'player6', 'player7', 'player8', 'player9', 'player10'), name='unique_players'),
        ),
    ]
