# Generated by Django 4.2.6 on 2024-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_fantasyteam_unique_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
