# Generated by Django 4.2.6 on 2024-03-19 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0016_thread_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
